#!/bin/sh
#
# chkconfig: 2345 55 25
# Description: Nginx init.d script, put in /etc/init.d, chmod +x /etc/init.d/zenix
#              For Debian, run: update-rc.d -f nginx defaults
#              For CentOS, run: chkconfig --add nginx
#
### BEGIN INIT INFO
# Provides:          zenix
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nginx init.d script
# Description:       Zenix is a full-fledged, fast and compact web application server based on Nginx core.
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Zenix"
NAME=zenix
PREFIX=/usr/local/zenix
DAEMON=$PREFIX/sbin/$NAME
CONF=$PREFIX/conf/zenix.conf
PID=$PREFIX/logs/$NAME.pid
SCRIPT=/etc/init.d/$NAME

if [ ! -x "$DAEMON" ] || [ ! -f "$CONF" ]; then
    echo "\033[33m $DAEMON has no permission to run. \033[0m"
    echo "\033[33m Or $CONF doesn't exist. \033[0m"
    sleep 1
    exit 1
fi

do_start() {
    if [ -f $PID ]; then
        echo "\033[33m $PID already exists. \033[0m"
        echo "\033[33m $DESC is already running or crashed. \033[0m"
        echo "\033[32m $DESC Reopening $CONF ... \033[0m"
        $DAEMON -s reopen -c $CONF
        sleep 1
        echo "\033[36m $DESC reopened. \033[0m"
    else
        echo "\033[32m $DESC Starting $CONF ... \033[0m"
        $DAEMON -c $CONF
        sleep 1
        echo "\033[36m $DESC started. \033[0m"
    fi
}

do_stop() {
    if [ ! -f $PID ]; then
        echo "\033[33m $PID doesn't exist. \033[0m"
        echo "\033[33m $DESC isn't running. \033[0m"
    else
        echo "\033[32m $DESC Stopping $CONF ... \033[0m"
        $DAEMON -s stop -c $CONF
        sleep 1
        echo "\033[36m $DESC stopped. \033[0m"
    fi
}

do_reload() {
    if [ ! -f $PID ]; then
        echo "\033[33m $PID doesn't exist. \033[0m"
        echo "\033[33m $DESC isn't running. \033[0m"
        echo "\033[32m $DESC Starting $CONF ... \033[0m"
        $DAEMON -c $CONF
        sleep 1
        echo "\033[36m $DESC started. \033[0m"
    else
        echo "\033[32m $DESC Reloading $CONF ... \033[0m"
        $DAEMON -s reload -c $CONF
        sleep 1
        echo "\033[36m $DESC reloaded. \033[0m"
    fi
}

do_start_reloader() {
	bold=`tput bold`
	normal=`tput sgr0`
	EVENTS="CREATE,CLOSE_WRITE,DELETE,MODIFY,MOVED_FROM,MOVED_TO"

    if [ -f $PID ]; then
        echo "\033[33m $PID already exists. \033[0m"
        echo "\033[33m $DESC is already running or crashed. \033[0m"
        echo "\033[32m Reopening Openresty ... \033[0m"
		$DAEMON -s reopen -c $CONF
        sleep 1
        echo "\033[32m Starting with autoreload ... \033[0m\nuse ${bold}CTRL+C${normal} to stop"
		while inotifywait -qqr -e "$EVENTS" $HOME/jembaz .
		do
			$DAEMON -s reload -c $CONF
		done
    else
        echo "\033[32m Starting with autoreload ... \033[0m\nuse ${bold}CTRL+C${normal} to stop"
		$DAEMON -c $CONF
		while inotifywait -qqr -e "$EVENTS" $HOME/jembaz .
		do
			$DAEMON -s reload -c $CONF
		done
    fi
}

do_quit() {
    if [ ! -f $PID ]; then
        echo "\033[33m $PID doesn't exist. \033[0m"
        echo "\033[33m $DESC isn't running. \033[0m"
    else
        echo "\033[32m $DESC Quitting $CONF ... \033[0m"
        $DAEMON -s quit -c $CONF
        sleep 1
        echo "\033[36m $DESC quitted. \033[0m"
    fi
}

do_test() {
    echo "\033[32m $DESC Testing $CONF ... \033[0m"
    $DAEMON -t -c $CONF
}

do_info() {
    $DAEMON -V
}

do_status() {
    if [ -f $PID ]; then
        echo "\033[32m $DESC is running \033[0m"
    else
        echo "\033[33m $DESC is not running \033[0m"
    fi
}

case "$1" in
 start)
 do_start
 ;;
 stop)
 do_stop
 ;;
 reload)
 do_reload
 ;;
 restart)
 do_stop
 do_start
 ;;
 quit)
 do_quit
 ;;
 test)
 do_test
 ;;
 info)
 do_info
 ;;
 status)
 do_status
 ;;
 start-reloader)
 do_start_reloader
 ;;
 *)
 echo "Usage: $SCRIPT {start|stop|reload|restart|quit|test|info|status|start-reloader}"
 exit 2
 ;;
esac

exit 0
